import math

class Orchestrator:
    @staticmethod
    def generate_remediation_plan(blast_radius_data):
        print(f"Orchestrating agentic decision pipeline for incident...")
        
        # Extract computed metrics from Layer 2
        revenue_at_risk = blast_radius_data["revenueAtRisk"]
        high_risk_vips = blast_radius_data["highRiskVips"]
        affected_sku = blast_radius_data["affectedSku"]
        
        # 1. CustomerAgent Evaluation
        customer_agent_recommendations = []
        loyalty_voucher_total = 0.0
        
        for vip in high_risk_vips:
            # Recommend $50 voucher compensation for high risk VIPs to preserve LTV
            voucher_val = 50.0
            loyalty_voucher_total += voucher_val
            customer_agent_recommendations.append({
                "customerName": vip["name"],
                "email": vip["email"],
                "recommendation": f"Issue ${voucher_val:.2f} credit voucher and email churn prevention letter.",
                "preservedLtv": vip["ltv"]
            })
            
        # 2. OperationsAgent Evaluation
        # Operations suggests an alternate local supplier B charging a 20% premium
        unit_premium_rate = 0.20
        estimated_premium_cost = revenue_at_risk * unit_premium_rate
        
        operations_recommendation = {
            "strategy": f"Source affected order SKUs from localized alternative Supplier B to bypass delay.",
            "priceMarkup": "20% Premium",
            "estimatedCost": estimated_premium_cost
        }
        
        # 3. FinanceAgent Evaluation
        # Calculates preservation ROI
        total_mitigation_cost = estimated_premium_cost + loyalty_voucher_total
        total_preserved_ltv = sum(vip["ltv"] for vip in high_risk_vips)
        
        roi_positive = total_preserved_ltv > total_mitigation_cost
        
        finance_recommendation = {
            "totalMitigationCost": total_mitigation_cost,
            "totalPreservedLtv": total_preserved_ltv,
            "decisionRoi": "POSITIVE" if roi_positive else "NEGATIVE",
            "approved": "PENDING_HUMAN_APPROVAL" if total_mitigation_cost >= 200.00 else "AUTO_APPROVED"
        }
        
        print(f"Remediation generated by Finance Agent: Net Preserved LTV=${total_preserved_ltv:.2f}, Total Cost=${total_mitigation_cost:.2f}")
        
        return {
            "incidentId": f"inc_{math.floor(revenue_at_risk)}_remedy",
            "blastRadius": {
                "sku": affected_sku,
                "revenueAtRisk": revenue_at_risk,
                "vipsCount": len(high_risk_vips)
            },
            "agentResponses": {
                "CustomerAgent": {
                    "vouchersIssuedCount": len(high_risk_vips),
                    "totalVoucherValue": loyalty_voucher_total,
                    "remedies": customer_agent_recommendations
                },
                "OperationsAgent": operations_recommendation,
                "FinanceAgent": finance_recommendation
            },
            "finalPlan": {
                "mitigation": "Bypass delay by sourcing alternative SKU from Supplier B + compensatory vouchers for affected VIPs.",
                "netCost": total_mitigation_cost,
                "netPreservedLtv": total_preserved_ltv,
                "status": finance_recommendation["approved"]
            }
        }
